import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-subcription',
  templateUrl: './subcription.component.html',
  styleUrls: ['./subcription.component.scss']
})
export class SubcriptionComponent implements OnInit {

  constructor() { }
  subscriptionHistoryDisplay=[];
  filtertoggle ='';
  subscriptionHistory = [
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'Active',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'Active',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'Active',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'Active',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'Active',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'Active',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'Active',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'Active',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'Active',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'Active',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'Active',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'Active',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'Active',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'Active',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'Active',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'Active',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'Active',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'Active',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'Active',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'Active',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'expire',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'expire',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'expire',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'expire',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
    {
      name: 'Husain Ali',
      email: 'alisdhfiohsidof@.com',
      subPlan: 'Gold Subscription',
      subDate: '10-10-2020',
      expDate: '10-10-2020',
      price:  '$199.00',
      status:  'expire',
      // actionRoute: 'this.assetsServices.getAssetsData(items)?.actionRoute',
      image: '../../../../../assets/Image/male.png',
    },
  ]
  filterHandler(value){
    console.log(value);
    this.filtertoggle=value;
    this.subscriptionHistoryDisplay=[...this.subscriptionHistory];
    this.subscriptionHistoryDisplay =this.subscriptionHistory.filter((el)=>el.status.toLowerCase() === value) 
  }
  ngOnInit(): void {
    this.subscriptionHistoryDisplay=[...this.subscriptionHistory];
  }

}
